<a href="https://colab.research.google.com/github/MuizSarwar/Deep-Learning-study-materials-/blob/main/Pytorch_training_pipe(deep_learning_cls_03)_A_better_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Libraries
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
#dataset load
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
#drop columns
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
#Target & Features
X = df.drop(['diagnosis'],axis=1) #Features
y = df['diagnosis'] #Target

#Train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [5]:
#Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
#Label Encoding on Target
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
#Numpy array to Pytorch tensor :

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
#data type conversion
X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
#data type conversion
y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

/tmp/ipykernel_671/4050742719.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
/tmp/ipykernel_671/4050742719.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
/tmp/ipykernel_671/4050742719.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
/tmp/ipykernel_671/4050742719.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

In [13]:
import torch.nn as nn
#Define the model:
class SimpleNN(nn.Module):
  def __init__(self,features_num):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(features_num,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [9]:
#parameters
learning_rate = 0.1
epochs = 25

In [14]:
loss_function = nn.BCELoss()

In [19]:
#Training Pipeline
model = SimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)

  #loss
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

  #zero gradient
  optimizer.zero_grad()

  #backward
  loss.backward()

  #parameters update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss}')

Epoch: 1, Loss: 0.6121241450309753
Epoch: 2, Loss: 0.4813691973686218
Epoch: 3, Loss: 0.4076983332633972
Epoch: 4, Loss: 0.3599782884120941
Epoch: 5, Loss: 0.32612913846969604
Epoch: 6, Loss: 0.30061763525009155
Epoch: 7, Loss: 0.28054293990135193
Epoch: 8, Loss: 0.2642303705215454
Epoch: 9, Loss: 0.2506418228149414
Epoch: 10, Loss: 0.23909763991832733
Epoch: 11, Loss: 0.22913281619548798
Epoch: 12, Loss: 0.2204177975654602
Epoch: 13, Loss: 0.21271184086799622
Epoch: 14, Loss: 0.20583468675613403
Epoch: 15, Loss: 0.1996483951807022
Epoch: 16, Loss: 0.19404534995555878
Epoch: 17, Loss: 0.18894019722938538
Epoch: 18, Loss: 0.18426424264907837
Epoch: 19, Loss: 0.17996150255203247
Epoch: 20, Loss: 0.17598581314086914
Epoch: 21, Loss: 0.17229855060577393
Epoch: 22, Loss: 0.16886740922927856
Epoch: 23, Loss: 0.16566479206085205
Epoch: 24, Loss: 0.1626671701669693
Epoch: 25, Loss: 0.1598542332649231

In [11]:
#Evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.75).float()
  accuracy = (y_pred == y_test_tensor).float().mean()  #Accuracy = (TP+TN)/(TP+TN+FP+FN)
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6083410382270813