<a href="https://colab.research.google.com/github/MuizSarwar/Deep-Learning-study-materials-/blob/main/text_representation(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Bag Of Words

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
# ==========================================
# 1. Documents (Corpus)
# ==========================================
corpus = [
    "students watch youtube youtube youtube",
    "youtube watch youtube",
    "students write comments",
    "youtube write comments"
]

In [3]:
cv = CountVectorizer()
X = cv.fit_transform(corpus)

In [4]:
#show vocabulary
cv.get_feature_names_out()

array(['comments', 'students', 'watch', 'write', 'youtube'], dtype=object)

In [6]:
#show words matrix
X.toarray()

array([[0, 1, 1, 0, 3],
       [0, 0, 1, 0, 2],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [8]:
#Dataframe representarion
df = pd.DataFrame(
    X.toarray(),
    index = ['D1','D2','D3','D4'],
    columns = cv.get_feature_names_out()
)

##TF-IDF

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
corpus = [
    "students watch youtube",
    "youtube watch youtube",
    "students write comments",
    "youtube write comments"
]

In [12]:
# ==========================================
# 1. Create Dataset
# ==========================================
df = pd.DataFrame({ "text" : corpus
    ,
    "output": [1, 1, 0, 0]
})

df

                      text  output
0   students watch youtube       1
1    youtube watch youtube       1
2  students write comments       0
3   youtube write comments       0

In [13]:
#TF-IDF vectorizer
tfidf = TfidfVectorizer()

In [14]:
#Learn Vocabulary + Compute TF-IDF
X = tfidf.fit_transform(df['text'])

In [17]:
#sparce matrix
X.toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [18]:
#features
tfidf.get_feature_names_out()

array(['comments', 'students', 'watch', 'write', 'youtube'], dtype=object)

In [23]:
##tf-idf matrix
tfidf_matrix = pd.DataFrame(
    X.toarray(),
    columns = tfidf.get_feature_names_out()
)

tfidf_matrix

   comments  students     watch     write   youtube
0  0.000000  0.613667  0.613667  0.000000  0.496816
1  0.000000  0.000000  0.525464  0.000000  0.850816
2  0.577350  0.577350  0.000000  0.577350  0.000000
3  0.613667  0.000000  0.000000  0.613667  0.496816